name: Update data

on:
   schedule:
   - cron: "0 13 * * 1-5"
   
  # Allows you to run this workflow manually from the Actions tab
   workflow_dispatch:
  
  # A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
   update:
     runs-on: ubuntu-latest
     env:
        GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
     steps:
       - uses: actions/checkout@v2
       - uses: r-lib/actions/setup-r@v2
         with:
           use-public-rspm: true

       - name: Install dependencies
         run: |
            install.packages(c("clipr","ggalt","RQuantLib","shinyWidgets","ggplot2", "jsonlite", "dplyr", "stringr", "lubridate", "derivmkts","pbapply","httr","rvest","purrr","data.table","quantmod"))
         shell: Rscript {0}

       - name: Update data
         run: |
          source("update_data.R")
         shell: Rscript {0}
  
       - name: Commit files
         run: |
           git config --local user.email "actions@github.com"
           git config --local user.name "GitHub Actions"
           git add --all
           git commit -am "add data"
           git push 
